<?php

declare(strict_types=1);

namespace CommerceWeavers\SyliusSaferpayPlugin\Payum\Action;

final class ErrorName
{
    public const ACTION_NOT_SUPPORTED = 'ACTION_NOT_SUPPORTED';

    public const ALIAS_INVALID = 'ALIAS_INVALID';

    public const AMOUNT_INVALID = 'AMOUNT_INVALID';

    public const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

    public const BLOCKED_BY_RISK_MANAGEMENT = 'BLOCKED_BY_RISK_MANAGEMENT';

    public const CARD_CHECK_FAILED = 'CARD_CHECK_FAILED';

    public const CARD_CVC_INVALID = 'CARD_CVC_INVALID';

    public const CARD_CVC_REQUIRED = 'CARD_CVC_REQUIRED';

    public const COMMUNICATION_FAILED = 'COMMUNICATION_FAILED';

    public const COMMUNICATION_TIMEOUT = 'COMMUNICATION_TIMEOUT';

    public const CONDITION_NOT_SATISFIED = 'CONDITION_NOT_SATISFIED';

    public const CURRENCY_INVALID = 'CURRENCY_INVALID';

    public const GENERAL_DECLINED = 'GENERAL_DECLINED';

    public const INTERNAL_ERROR = 'INTERNAL_ERROR';

    public const NO_CONTRACT = 'NO_CONTRACT';

    public const NO_CREDITS_AVAILABLE = 'NO_CREDITS_AVAILABLE';

    public const PAYER_AUTHENTICATION_REQUIRED = 'PAYER_AUTHENTICATION_REQUIRED';

    public const PAYMENTMEANS_INVALID = 'PAYMENTMEANS_INVALID';

    public const PAYMENTMEANS_NOT_SUPPORTED = 'PAYMENTMEANS_NOT_SUPPORTED';

    public const PERMISSION_DENIED = 'PERMISSION_DENIED';

    public const THREE_DS_AUTHENTICATION_FAILED = '3DS_AUTHENTICATION_FAILED';

    public const TOKEN_EXPIRED = 'TOKEN_EXPIRED';

    public const TOKEN_INVALID = 'TOKEN_INVALID';

    public const TRANSACTION_ABORTED = 'TRANSACTION_ABORTED';

    public const TRANSACTION_ALREADY_CAPTURED = 'TRANSACTION_ALREADY_CAPTURED';

    public const TRANSACTION_DECLINED = 'TRANSACTION_DECLINED';

    public const TRANSACTION_IN_WRONG_STATE = 'TRANSACTION_IN_WRONG_STATE';

    public const TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND';

    public const TRANSACTION_NOT_STARTED = 'TRANSACTION_NOT_STARTED';

    public const UNEXPECTED_ERROR_BY_ACQUIRER = 'UNEXPECTED_ERROR_BY_ACQUIRER';

    public const UPDATE_CARD_INFORMATION = 'UPDATE_CARD_INFORMATION';

    public const VALIDATION_FAILED = 'VALIDATION_FAILED';

    private function __construct()
    {
    }
}
