commerce_weavers_saferpay_transaction_log:
    resource: |
        alias: commerce_weavers_saferpay.transaction_log
        section: admin
        templates: "@SyliusAdmin\\Crud"
        only: ['index', 'show']
        redirect: update
        grid: commerce_weavers_saferpay_transaction_log
        vars:
            index:
                icon: 'th list'
    type: sylius.resource
    prefix: saferpay
    
commerce_weavers_saferpay_admin_transaction_log_show:
    path: /saferpay/transaction-logs/{id}
    methods: [ GET ]
    defaults:
        _controller: commerce_weavers_saferpay.controller.transaction_log::showAction
        _sylius:
            template: '@CommerceWeaversSyliusSaferpayPlugin/Admin/TransactionLogs/show.html.twig'

commerce_weavers_sylius_saferpay_admin_configure_payment_methods:
    path: /payment-methods/{id}/configure-saferpay-payment-methods
    methods: [GET, POST]
    defaults:
        _controller: CommerceWeavers\SyliusSaferpayPlugin\Controller\Action\ConfigurePaymentMethodsAction
