commerce_weavers_sylius_saferpay_admin_transaction_log_index:
    resource: |
        alias: commerce_weavers_saferpay.transaction_log
        section: admin
        templates: "@SyliusAdmin\\Crud"
        only: ['index']
        redirect: update
        grid: commerce_weavers_saferpay_transaction_log
        vars:
            index:
                icon: 'th list'
    type: sylius.resource
    prefix: saferpay
