commerce_weavers_sylius_saferpay_admin_transaction_log_index:
    resource: |
        alias: commerce_weavers_saferpay.transaction_log
        section: admin
        templates: "@SyliusAdmin\\Crud"
        only: ['index']
        redirect: update
        grid: commerce_weavers_saferpay_transaction_log
        vars:
            index:
                icon: 'th list'
    type: sylius.resource
    prefix: saferpay

sylius_admin_order_payment_refund:
    path: /orders/{orderId}/payments/{id}/refund
    methods: [PUT]
    defaults:
        _controller: CommerceWeavers\SyliusSaferpayPlugin\Controller\Action\PrepareRefundAction
        _sylius:
            redirect:
                route: commerce_weavers_sylius_saferpay_refund_payment

commerce_weavers_sylius_saferpay_refund_payment:
    path: /payment/saferpay/refund/{payum_token}
    methods: [GET, POST]
    defaults:
        _controller: CommerceWeavers\SyliusSaferpayPlugin\Controller\Action\RefundAction
